<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <StartupObject>Playnite.FullscreenApp.ProgramEntry</StartupObject>
    <ApplicationIcon>Themes\Fullscreen\Default\Images\applogo.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PostBuildEvent>SETX PLAYNITE_SLN $(SolutionDir)</PostBuildEvent>
    <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
    <LargeAddressAware>true</LargeAddressAware>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
    <OutputPath>bin\x86\Debug\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x86'">
    <OutputPath>bin\x86\Release\</OutputPath>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <OutputPath>bin\x64\Debug\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\x64\Release\</OutputPath>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="CommonServiceLocator" Version="2.0.7" />
    <PackageReference Include="LargeAddressAware" Version="1.0.6" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.7" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.7" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="Prism.Container.Abstractions" Version="9.0.107" />
    <PackageReference Include="Prism.Core" Version="9.0.537" />
    <PackageReference Include="Prism.Events" Version="9.0.537" />
    <PackageReference Include="Prism.Wpf" Version="9.0.537" />
    <PackageReference Include="System.IO.Abstractions" Version="22.0.15" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
    <PackageReference Include="System.Security.AccessControl" Version="6.0.1" />
    <PackageReference Include="TestableIO.System.IO.Abstractions" Version="22.0.15" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.Wrappers" Version="22.0.15" />
    <PackageReference Include="Testably.Abstractions.FileSystem.Interface" Version="9.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.7" />
  </ItemGroup>
  <ItemGroup>
    <SplashScreen Include="SplashScreen.png" />
    <Resource Include="..\..\references\Fonts\*.*">
      <Link>Fonts\%(Filename)%(Extension)</Link>
    </Resource>
    <None Include="..\Playnite\license.txt">
      <Link>license.txt</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Content Include="Themes\Fullscreen\Default\audio\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Update="Themes\Fullscreen\Default\Images\custom_cover_background.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Themes\Fullscreen\Default\Images\applogo.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Themes\Fullscreen\Default\Images\applogo_full.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Themes\Fullscreen\Default\theme.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Themes\Fullscreen\Default\Images\applogo_clean.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Themes\Fullscreen\Default\DescriptionView.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Themes\Fullscreen\Default\Images\applogo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PlayniteSDK\Playnite.SDK.csproj" />
    <ProjectReference Include="..\Playnite\Playnite.Legacy.csproj" />
  </ItemGroup>
</Project>