<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\references\CefSharpRedist\concrt140.dll" TargetPath="%(Filename)%(Extension)" Link="concrt140.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\references\CefSharpRedist\msvcp140.dll" TargetPath="%(Filename)%(Extension)" Link="msvcp140.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\references\CefSharpRedist\msvcp140_1.dll" TargetPath="%(Filename)%(Extension)" Link="msvcp140_1.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\references\CefSharpRedist\msvcp140_2.dll" TargetPath="%(Filename)%(Extension)" Link="msvcp140_2.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\references\CefSharpRedist\msvcp140_atomic_wait.dll" TargetPath="%(Filename)%(Extension)" Link="msvcp140_atomic_wait.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\references\CefSharpRedist\msvcp140_codecvt_ids.dll" TargetPath="%(Filename)%(Extension)" Link="msvcp140_codecvt_ids.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\references\CefSharpRedist\vccorlib140.dll" TargetPath="%(Filename)%(Extension)" Link="vccorlib140.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\references\CefSharpRedist\vcruntime140.dll" TargetPath="%(Filename)%(Extension)" Link="vcruntime140.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="Flurl" Version="4.0.0" />
    <PackageReference Include="LiteDB" Version="5.0.21" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.8" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\DesignBackground.jpg" />
    <Resource Include="Resources\Images\DesignCover.jpg" />
    <Resource Include="Resources\Images\DesignIcon.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="gamecontrollerdb.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Localization\locstatus.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\playnite_extension.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Safe Mode.bat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Playnite.SDK\Playnite.SDK.csproj" />
  </ItemGroup>

</Project>
